dist: trusty
language: php

php:
    - 7.4
    - hhvm

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - vendor/bin/phpcs --standard=psr1 src/
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
